ATIM/config/routes.rb
ATIM::Application.routes.draw do

  resources :meeting_notes

  resources :commitments

  resources :meetings

  resources :deliverables

  resources :students

  get  'sources/new'         => 'sources#new'
  post 'sources/new'         => 'sources#create'
  get  'sources/:id'         => 'sources#search'
  get  'sources/:id/edit'    => 'sources#analysis'
  put  'sources/update'      => 'sources#update'

  resources :sources

  match 'commitments/:id'      => 'commitments#search'
  match 'commitments/:id/edit' => 'commitments#close'

  resources :commitments

  get "commitments/create"
  get "commitments/edit"
  get "commitments/close"

  resources :recommendations

  resources :theses

  get "index/index"

  resources :teachers

  get "home/login"

  get "home/sign"

  root  to: 'home#login'

  match '/commitmentsSearch', to: 'commitments#search', :as => 'commitmentsSearch'
  match '/meetingsStudent', to: 'index#meetings', :as => 'meetingsStudent'
  match '/indexStudent', to: 'index#indexUsuario', :as => 'indexUsuario'
  match '/newResource', to: 'index#createResource', :as => 'createResource'
  match '/updateResource', to: 'index#updateResource', :as => 'updateResource'
  match '/entregas', to: 'index#indexDeliverable', :as => 'indexDeliverable'
  match '/stateOfArt', to: 'index#resourcesIndex', :as => 'resourcesIndex'
  match '/commitmentsStudent', to: 'index#commitments', :as => 'commitmentsStudent'
  match '/signup', to: 'teachers#new', :as => 'signup'
  match '/index', to: 'index#index', :as => 'index'

   match '/ranking', to: 'index#comenzarTesis', :as=> 'comenzar'

end

ATIM/app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :thesis
  validates_presence_of :title, :fecha, :thesis_id
  has_many :commitments
  has_many :meeting_notes

end

ATIM/app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @thesis = Thesis.find(params[:thesis_id])
    @meeting = Meeting.new(params[:meeting])
    @meeting.thesis_id = @thesis.id

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to index_path(:email=>params[:emailTeacher]), notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { redirect_to index_path(:email=>params[:emailTeacher]), notice: @student.errors.full_messages}
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end
end

ATIM/app/helpers/meetings_helper.rb
module MeetingsHelper
end

ATIM/app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ATIM/app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

ATIM/app/views/meetings/index.html.erb
<h1>Listing meetings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetings.each do |meeting| %>
  <tr>
    <td><%= link_to 'Show', meeting %></td>
    <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
    <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meeting', new_meeting_path %>

ATIM/app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

ATIM/app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>