ATIM/config/routes.rb
ATIM::Application.routes.draw do

  resources :meeting_notes

  resources :commitments

  resources :meetings

  resources :deliverables

  resources :students

  get  'sources/new'         => 'sources#new'
  post 'sources/new'         => 'sources#create'
  get  'sources/:id'         => 'sources#search'
  get  'sources/:id/edit'    => 'sources#analysis'
  put  'sources/update'      => 'sources#update'

  resources :sources

  match 'commitments/:id'      => 'commitments#search'
  match 'commitments/:id/edit' => 'commitments#close'

  resources :commitments

  get "commitments/create"
  get "commitments/edit"
  get "commitments/close"

  resources :recommendations

  resources :theses

  get "index/index"

  resources :teachers

  get "home/login"

  get "home/sign"

  root  to: 'home#login'

  match '/commitmentsSearch', to: 'commitments#search', :as => 'commitmentsSearch'
  match '/meetingsStudent', to: 'index#meetings', :as => 'meetingsStudent'
  match '/indexStudent', to: 'index#indexUsuario', :as => 'indexUsuario'
  match '/newResource', to: 'index#createResource', :as => 'createResource'
  match '/updateResource', to: 'index#updateResource', :as => 'updateResource'
  match '/entregas', to: 'index#indexDeliverable', :as => 'indexDeliverable'
  match '/stateOfArt', to: 'index#resourcesIndex', :as => 'resourcesIndex'
  match '/commitmentsStudent', to: 'index#commitments', :as => 'commitmentsStudent'
  match '/signup', to: 'teachers#new', :as => 'signup'
  match '/index', to: 'index#index', :as => 'index'

   match '/ranking', to: 'index#comenzarTesis', :as=> 'comenzar'

end

ATIM/app/models/teacher.rb
class Teacher < ActiveRecord::Base

	validates_presence_of :name, :email
	has_many :theses
	validates_uniqueness_of :email

	def self.search(search)
	  if search
	    find(:all, :conditions => ['email = ?', "#{search}"]).first
	  end
	end
end

ATIM/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  
  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teachers }
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.json
  def new
    @teacher = Teacher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(params[:teacher])
    respond_to do |format|
      if @teacher.save
        format.html { redirect_to root_path, notice: 'Teacher was successfully created.' }
        format.json { render json: @teacher, status: :created, location: @teacher }
      else
        format.html { render action: "new" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.json
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end
end

ATIM/app/helpers/teachers_helper.rb
module TeachersHelper
end

ATIM/app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ATIM/app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

ATIM/app/views/teachers/index.html.erb
<h1>Listing teachers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @teachers.each do |teacher| %>
  <tr>
    <td><%= teacher.name %></td>
    <td><%= teacher.email %></td>
    <td><%= link_to 'Show', teacher %></td>
    <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
    <td><%= link_to 'Destroy', teacher, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Teacher', new_teacher_path %>

ATIM/app/views/teachers/new.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
	<tr><td>&nbsp;</td></tr>
	<tr><td>&nbsp;</td></tr>	
  </table>
	<table class="form-signin">
	      <tr>
	          <td><h1 class="form-signin-heading">New Teacher</h1></td>
	      </tr>
	      <tr>
	          <td> <%= f.text_field :name, :placeholder => 'Complete name' %></td>
	      </tr>
	      <tr>
	          <td> <%= f.text_field :email, :placeholder => 'Email'%></td>
	      </tr>
	      <tr><td>&nbsp;</td></tr>
	      <tr><td><%= f.submit "Sign up",  class: "btn"%> </tr></td>
	      <tr><td><%= link_to 'Atras', root_path%> </tr></td>
		</td></tr>
	</table>
<% end %>

ATIM/app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @teacher.name %>
</p>

<p>
  <b>Email:</b>
  <%= @teacher.email %>
</p>


<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>