ATIM/config/routes.rb
ATIM::Application.routes.draw do

  resources :meeting_notes

  resources :commitments

  resources :meetings

  resources :deliverables

  resources :students

  get  'sources/new'         => 'sources#new'
  post 'sources/new'         => 'sources#create'
  get  'sources/:id'         => 'sources#search'
  get  'sources/:id/edit'    => 'sources#analysis'
  put  'sources/update'      => 'sources#update'

  resources :sources

  match 'commitments/:id'      => 'commitments#search'
  match 'commitments/:id/edit' => 'commitments#close'

  resources :commitments

  get "commitments/create"
  get "commitments/edit"
  get "commitments/close"

  resources :recommendations

  resources :theses

  get "index/index"

  resources :teachers

  get "home/login"

  get "home/sign"

  root  to: 'home#login'

  match '/commitmentsSearch', to: 'commitments#search', :as => 'commitmentsSearch'
  match '/meetingsStudent', to: 'index#meetings', :as => 'meetingsStudent'
  match '/indexStudent', to: 'index#indexUsuario', :as => 'indexUsuario'
  match '/newResource', to: 'index#createResource', :as => 'createResource'
  match '/updateResource', to: 'index#updateResource', :as => 'updateResource'
  match '/entregas', to: 'index#indexDeliverable', :as => 'indexDeliverable'
  match '/stateOfArt', to: 'index#resourcesIndex', :as => 'resourcesIndex'
  match '/commitmentsStudent', to: 'index#commitments', :as => 'commitmentsStudent'
  match '/signup', to: 'teachers#new', :as => 'signup'
  match '/index', to: 'index#index', :as => 'index'

   match '/ranking', to: 'index#comenzarTesis', :as=> 'comenzar'

end

ATIM/app/models/meeting_note.rb
class MeetingNote < ActiveRecord::Base
  validates_presence_of :note
  belongs_to :meeting
  belongs_to :thesis


end

ATIM/app/controllers/meeting_notes_controller.rb
class MeetingNotesController < ApplicationController
  # GET /meeting_notes
  # GET /meeting_notes.json
  def index
    @meeting_notes = MeetingNote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meeting_notes }
    end
  end

  # GET /meeting_notes/1
  # GET /meeting_notes/1.json
  def show
    @meeting_note = MeetingNote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting_note }
    end
  end

  # GET /meeting_notes/new
  # GET /meeting_notes/new.json
  def new
    @meeting_note = MeetingNote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting_note }
    end
  end

  # GET /meeting_notes/1/edit
  def edit
    @meeting_note = MeetingNote.find(params[:id])
  end

  # POST /meeting_notes
  # POST /meeting_notes.json
  def create
    @meeting_note = MeetingNote.new(params[:meeting_note])
    @thesis = Thesis.find(params[:thesis_id])
    @meeting = Meeting.find(params[:idMeeting])
    @meeting_note.thesis = @thesis
    @meeting_note.meeting = @meeting

    respond_to do |format|
      if @meeting_note.save
        format.html { redirect_to meetingsStudent_path(:email=>params[:email],:id=>@thesis), notice: 'Note updated.' }
      else
        format.html { redirect_to meetingsStudent_path(:email=>params[:email],:id=>@thesis), notice: @meeting_note.errors.full_messages}
      end
    end
  end

  # PUT /meeting_notes/1
  # PUT /meeting_notes/1.json
  def update
    @meeting_note = MeetingNote.find(params[:id])

    respond_to do |format|
      if @meeting_note.update_attributes(params[:meeting_note])
        format.html { redirect_to @meeting_note, notice: 'Meeting note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meeting_notes/1
  # DELETE /meeting_notes/1.json
  def destroy
    @meeting_note = MeetingNote.find(params[:id])
    @meeting_note.destroy

    respond_to do |format|
      format.html { redirect_to meeting_notes_url }
      format.json { head :no_content }
    end
  end
end

ATIM/app/helpers/meeting_notes_helper.rb
module MeetingNotesHelper
end

ATIM/app/views/meeting_notes/_form.html.erb
<%= form_for(@meeting_note) do |f| %>
  <% if @meeting_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting_note.errors.count, "error") %> prohibited this meeting_note from being saved:</h2>

      <ul>
      <% @meeting_note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ATIM/app/views/meeting_notes/edit.html.erb
<h1>Editing meeting_note</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting_note %> |
<%= link_to 'Back', meeting_notes_path %>

ATIM/app/views/meeting_notes/index.html.erb
<h1>Listing meeting_notes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meeting_notes.each do |meeting_note| %>
  <tr>
    <td><%= link_to 'Show', meeting_note %></td>
    <td><%= link_to 'Edit', edit_meeting_note_path(meeting_note) %></td>
    <td><%= link_to 'Destroy', meeting_note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meeting note', new_meeting_note_path %>

ATIM/app/views/meeting_notes/new.html.erb
<h1>New meeting_note</h1>

<%= render 'form' %>

<%= link_to 'Back', meeting_notes_path %>

ATIM/app/views/meeting_notes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_meeting_note_path(@meeting_note) %> |
<%= link_to 'Back', meeting_notes_path %>